name: Auto Tweet Using AI

# Runs every hour
on:
  schedule:
    - cron: "*/30 * * * *" # Run every 30 minutes

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Introduce random delay
        run: |
          # Generate a random delay between 0 and 1800 seconds (30 minutes)
          DELAY=$((30 * 60 + RANDOM % (30 * 60)))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY
      - name: Install Dependencies
        run: npm i
      - name: Run Twitter bot
        run: npm start
